---
title: "Occurrence"
format: html
editor: visual
---

### 1. Get species list

```{r}
library(googledrive)
library(googlesheets4)

# Authoritization
drive_auth()
gs4_auth(token = drive_token())

# Get data
ss <- drive_get("Special Status Species")

## E.g. sheet names
ss_meta <- gs4_get(ss) 
sheet_names <- ss_meta$sheets$name

dat <- read_sheet(ss, sheet = sheet_names[1])
head(dat)

# Get species' names
scientific_names_df <- dat[, c("Name (common)", "Name (Latin)")]

# Use Latin name for searching
scientific_names <- scientific_names_df$`Name (Latin)`

```

### 2. Get information from gbif

```{r}
pkgs <- c("here", "sf", "dplyr", "rgbif")
for (pkg in pkgs){
  if (!require(pkg, character.only = TRUE)) {
    install.packages(pkg)
    require(pkg, character.only = TRUE)
  }
}; rm(pkgs, pkg)

library(here)
library(sf)
library(dplyr)
library(rgbif)

# Set a directory for data
#occ_dir <- here("/occurrences")
#  if (!dir.exists(occ_dir)) dir.create(occ_dir)

occ_dir <- "E:/OneDrive/UCSB/Class/GEOG274/code/GEOG274-XUE/data/occurrences"
if (!dir.exists(occ_dir)) dir.create(occ_dir, recursive = TRUE)
```

```{r}
# log in gbif
install.packages("usethis")
library(usethis)
usethis::edit_r_environ() 

#https://docs.ropensci.org/rgbif/articles/gbif_credentials.html
```

```{r}
# Confirm names used in GBIF database for your species list
gbif_names <- name_backbone_checklist(scientific_names)

# Only keep valid records
gbif_names <- gbif_names[!is.na(gbif_names$usageKey), ]

# Spin up a download request for GBIF occurrence data
# Reference
# https://docs.ropensci.org/rgbif/articles/getting_occurrence_data.html
# https://data-blog.gbif.org/post/downloading-long-species-lists-on-gbif/

occ_meta <- occ_download(
  pred_in("taxonKey", unique(gbif_names$usageKey)),
  pred("occurrenceStatus", "PRESENT"), 
  pred("hasCoordinate", TRUE), pred("hasGeospatialIssue", FALSE),
  pred_not(pred_in("basisOfRecord",
                   c("FOSSIL_SPECIMEN","LIVING_SPECIMEN"))),
  format = "SIMPLE_CSV")

# Save out the name catalog using the GBIF query unique ID in name to pair.
write.csv(gbif_names, 
          file.path(occ_dir, sprintf("gbif_names275_%s.csv", occ_meta)),
          row.names = FALSE)

# Download the occurrences
status <- occ_download_wait(occ_meta)
if (status$status == "SUCCEEDED"){
  d <- occ_download_get(occ_meta, path = occ_dir, overwrite = TRUE)
} else {
  warning(sprintf("The request %s.", status$status))
  d <- NULL
}
```

```{r}
# Check if the downloaded data include all species in our list
download_gbif <- read.csv("E:/OneDrive/UCSB/Class/GEOG274/code/GEOG274-XUE/data/occurrences/Plant-occurrence-gbif.csv", stringsAsFactors = FALSE)

unique_species <- unique(download_gbif$taxonKey)
length(unique_species)

missing_from_list <- setdiff(gbif_names$usageKey, unique_species)
length(missing_from_list)  
# 3691920 5699909

# Find the missing species
missing_species_names <- gbif_names$canonicalName[gbif_names$usageKey %in% missing_from_list]

print(missing_species_names)
#"Erysimum suffrutescens grandifolium" "Malacothrix incana succulenta"

```

```{r}
# Clip data to target counties
install.packages("tigris") # for download county boundary
library(tigris)

ca_counties <- counties(state = "CA", cb = TRUE)
target_counties <- ca_counties %>%
  filter(NAME %in% c("Santa Barbara", "Ventura", "San Luis Obispo"))

# Convert .csv occurrence data to sf object (spatial data)
occ_sf <- st_as_sf(download_gbif, coords = c("decimalLongitude", "decimalLatitude"), crs = 4326)

# Keep same coordinate reference system
occ_sf <- st_transform(occ_sf, st_crs(target_counties))

# Clip to target counties
occ_in_target <- st_intersection(occ_sf, target_counties)

# Check data distribution
plot(st_geometry(target_counties), col = "lightblue", border = "black", main = "GBIF Data Points within Target Counties")
plot(st_geometry(occ_in_target), add = TRUE, col = "red", pch = 20)

coordinates <- st_coordinates(occ_in_target)
occ_in_target_df <- as.data.frame(occ_in_target)
occ_in_target_df$decimalLongitude <- coordinates[, 1] 
occ_in_target_df$decimalLatitude <- coordinates[, 2]  

write.csv(occ_in_target_df, 
          file.path(occ_dir, "Plant-Gbif-occ-targetCounty.csv"),
          row.names = FALSE)
```
