# Author: Olivia Ross
# Date: 9 April 2025

# This script reads in Calflora occurence data from Ventura, Santa Barbara, 
# and San Luis Obispo counties and creates a unique plant list 

# List was generated by selecting counties of interest and "rare" species 
# on Calflora "Observation Download", data accessed 9 April 2025

# packages 
librarian:: shelf("dplyr", "here")

# reading in plant observations from Calflora 
plants_raw <- read.csv(here("data/calflora-out-2.csv"))

# creating a df with each unique combination of common name, species name and county
# this way we can capture plants that exist in multiple counties if we switch 
# the county filter
plant_county <- plants_raw |>
  select(Common.Name, Plant, County) |>
  distinct(Common.Name, Plant, County)

# filtering Santa Barbara County
plants_SB <- plant_county |>
  filter(County == "Santa Barbara")

# exporting as csv 
# on Olivia local, but pasted into Special Status Species google sheet on 
# "Special Status Species" spreadsheet
write.csv(plants_SB, here("data/plants_SB.csv"))